version: "3"

services:
  postgresdb:
      image: postgres:latest
      container_name: postgresdb
      restart: always
      environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      volumes:
        - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        - postgres_data:/var/lib/postgresql/data/

  web:
    image: anra/reg_vcs:latest
    container_name:   web
    environment:
      # Mode
      - MODE_DEBUG=${MODE_DEBUG}
      - MODE_ALLOWED_HOSTS=${MODE_ALLOWED_HOSTS}
      # Database
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      # Telegram
      - BOT_API_TOKEN=${BOT_API_TOKEN}
      - BOT_NAME=${BOT_NAME}
      # Email
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      # Default Django admin user
      - DJANGO_ADMIN_NAME=${DJANGO_ADMIN_NAME}
      - DJANGO_ADMIN_PASSWORD=${DJANGO_ADMIN_PASSWORD}
      - DJANGO_ADMIN_EMAIL=${DJANGO_ADMIN_EMAIL}
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - postgresdb

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - web
    ports:
    - 80:80

volumes:
  postgres_data:
  static_volume:
  media_volume: