# Generated by Django 3.1.7 on 2021-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='urls',
            field=models.TextField(blank=True, help_text='Перечислите url-адреса страниц на которых будет автоматически отображатся страница помощи. например: /schedule/event-create/', null=True, verbose_name='Страницы для автоматического вывода'),
        ),
    ]
