# Generated by Django 3.1.7 on 2022-10-22 08:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20221022_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time_start'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_start',
        ),
        migrations.AddField(
            model_name='event',
            name='booking_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_booking_assistant', to=settings.AUTH_USER_MODEL, verbose_name='Ассистент'),
        ),
        migrations.AddField(
            model_name='event',
            name='booking_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='event',
            name='booking_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.room', verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='event',
            name='booking_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Черновик'), (2, 'Ожидание'), (3, 'Готово'), (4, 'Отказ'), (5, 'Окончено')], default=1, null=True, verbose_name='Статус бронирования'),
        ),
        migrations.AddField(
            model_name='event',
            name='conf_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='event',
            name='conf_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='conf_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='event',
            name='conf_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='event',
            name='conf_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_conference_operator', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='event',
            name='conf_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.server', verbose_name='Сервер'),
        ),
        migrations.AddField(
            model_name='event',
            name='conf_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Черновик'), (2, 'Ожидание'), (3, 'Готово'), (4, 'Отказ'), (5, 'Окончено')], default=1, null=True, verbose_name='Статус видеоконференции'),
        ),
        migrations.AddField(
            model_name='event',
            name='quota',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2022, 10, 22, 11, 24, 6, 807139), verbose_name='Время окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time_start',
            field=models.TimeField(default=datetime.time(11, 25, 45, 706158), verbose_name='Время начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='with_booking',
            field=models.BooleanField(default=False, verbose_name='Нужно помещение'),
        ),
        migrations.AddField(
            model_name='event',
            name='with_conf',
            field=models.BooleanField(default=False, verbose_name='Нужна видео конференция'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 22), verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Черновик'), (2, 'Ожидание'), (3, 'Готово'), (4, 'Отказ'), (5, 'Окончено')], default=1, verbose_name='Статус мероприятия'),
        ),
    ]
