# Generated by Django 3.1.7 on 2022-10-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20221022_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='quota',
            new_name='conf_number_clients',
        ),
    ]
