# Generated by Django 3.1.7 on 2022-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20221022_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_description',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='booking_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Создание'), (2, 'Ожидание'), (3, 'Готово'), (4, 'Отказ'), (5, 'Окончено')], default=1, null=True, verbose_name='Статус бронирования'),
        ),
        migrations.AlterField(
            model_name='event',
            name='conf_description',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='conf_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Создание'), (2, 'Ожидание'), (3, 'Готово'), (4, 'Отказ'), (5, 'Окончено')], default=1, null=True, verbose_name='Статус видеоконференции'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Создание'), (2, 'Ожидание'), (3, 'Готово'), (4, 'Отказ'), (5, 'Окончено')], default=1, verbose_name='Статус мероприятия'),
        ),
    ]
