# Generated by Django 3.1.7 on 2022-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20221022_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='booking_description',
            new_name='booking_note',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='conf_description',
            new_name='conf_note',
        ),
        migrations.RemoveField(
            model_name='event',
            name='booking_comment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='conf_comment',
        ),
        migrations.AddField(
            model_name='event',
            name='booking_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='event',
            name='conf_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
    ]
