# Generated by Django 3.1.7 on 2022-10-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20221022_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='applications',
        ),
        migrations.AddField(
            model_name='room',
            name='server',
            field=models.ManyToManyField(related_name='related_room', to='schedule.Server', verbose_name='Доступные серверы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='with_conf',
            field=models.BooleanField(default=False, verbose_name='Нужна видеоконференция'),
        ),
    ]
