# Generated by Django 3.1.7 on 2022-10-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20221022_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='server_type',
        ),
        migrations.AddField(
            model_name='server',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Внешний сервер'), (2, 'Внутренний сервер')], default=1, verbose_name='Тип сервера'),
        ),
    ]
