# Generated by Django 3.1.7 on 2022-10-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20221022_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booking_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.room', verbose_name='Место проведения'),
        ),
    ]
