# Generated by Django 3.1.7 on 2022-10-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_auto_20221023_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='room',
            field=models.ManyToManyField(to='schedule.Room', verbose_name='Доступные помещения'),
        ),
    ]
