# Generated by Django 3.1.7 on 2022-11-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20221023_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='event',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='server',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
    ]
