# Generated by Django 3.1.6 on 2021-02-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210221_1617'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='schedule.Staffer', verbose_name='Получатель'),
        ),
    ]
