# Generated by Django 3.1.6 on 2021-02-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210221_1617'),
        ('dispatch', '0002_auto_20210221_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ManyToManyField(blank=True, to='schedule.Staffer', verbose_name='Получатель'),
        ),
    ]
