# Generated by Django 3.1.6 on 2021-03-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20210305_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='help.section', verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
