# Generated by Django 3.1.6 on 2021-03-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_auto_20210306_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body_text',
            field=models.TextField(verbose_name='Содержание страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='page',
            name='serial_number',
            field=models.SmallIntegerField(verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='section',
            name='serial_number',
            field=models.SmallIntegerField(default=666, unique=True, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
