# Generated by Django 3.1.6 on 2021-02-21 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210220_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name'], 'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'time_start'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['date', 'time_start'], 'verbose_name': 'Конференция', 'verbose_name_plural': 'Конференции'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['created_at'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['address'], 'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
        migrations.AlterModelOptions(
            name='staffer',
            options={'ordering': ['name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.staffer', verbose_name='Сотрудник'),
        ),
    ]
