# Generated by Django 3.1.7 on 2021-03-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210313_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('wait', 'Ожидание'), ('ready', 'Готово'), ('rejection', 'Отказ'), ('completed', 'Окончено')], default='draft', max_length=100, verbose_name='Статус мероприятия'),
        ),
    ]
