# Generated by Django 3.1.7 on 2021-03-13 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210313_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='server',
            name='responsible',
        ),
        migrations.AddField(
            model_name='room',
            name='assistants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Ассистенты'),
        ),
        migrations.AddField(
            model_name='server',
            name='operators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Операторы'),
        ),
    ]
