# Generated by Django 3.1.6 on 2021-02-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210221_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='telegram',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Телеграм чат-id'),
        ),
    ]
