# Generated by Django 3.1.6 on 2021-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20210221_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='without_conference',
            field=models.BooleanField(default=False, verbose_name='Без конференции'),
        ),
    ]
