# Generated by Django 3.1.6 on 2021-02-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20210225_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date_start'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала мероприятия'),
        ),
    ]
