# Generated by Django 3.1.6 on 2021-03-06 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20210227_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='link_to_event',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='application',
            name='quota',
        ),
        migrations.RemoveField(
            model_name='application',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='application',
            name='server_name',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='application',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='type',
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сервера')),
                ('server_address', models.CharField(max_length=50, verbose_name='Имя сервера')),
                ('quota', models.PositiveSmallIntegerField(verbose_name='Количество лицензий')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('server_type', models.CharField(choices=[('external', 'Внешний'), ('local', 'Внутренний')], default='local', max_length=100, verbose_name='Тип сервера')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.application', verbose_name='Приложение')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.staffer', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Сервера',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='conference',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.server', verbose_name='Сервер'),
        ),
    ]
