# Generated by Django 3.1.6 on 2021-03-06 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20210306_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.application', verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='server',
            name='quota',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество лицензий'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес сервера'),
        ),
    ]
