# Generated by Django 3.1.6 on 2021-03-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20210307_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='conference',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('external', 'Внешний сервер'), ('local', 'Внутренний сервер')], default='local', max_length=100, verbose_name='Тип сервера'),
        ),
    ]
