# Generated by Django 3.1.6 on 2021-02-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название приложения')),
                ('server_name', models.CharField(max_length=50, verbose_name='Имя сервера')),
                ('number_of_licenses', models.PositiveSmallIntegerField(verbose_name='Количество лицензий')),
            ],
        ),
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('room', models.CharField(max_length=255, verbose_name='Комната')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('applications', models.ManyToManyField(related_name='related_room', to='main.Application', verbose_name='Приложения')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staffer', verbose_name='Ответственный сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staffer', verbose_name='Ответственный сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_of_event', models.DateTimeField(verbose_name='Дата проведения')),
                ('number_of_participants', models.PositiveSmallIntegerField(verbose_name='Количество участников')),
                ('type_event', models.CharField(choices=[('external', 'Внешнее'), ('local', 'Внутренее')], default='external', max_length=100, verbose_name='Тип мероприятия')),
                ('status', models.CharField(choices=[('created', 'Мероприятие создано'), ('is_ready', 'Подготовка окончена'), ('completed', 'Окончено')], default='created', max_length=100, verbose_name='Статус мероприятия')),
                ('link_to_event', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application', verbose_name='Приложение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization', verbose_name='Организация')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staffer', verbose_name='Ответственный сотрудник')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Место проведения')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staffer', verbose_name='Ответственный сотрудник'),
        ),
    ]
