# Generated by Django 3.1.6 on 2021-02-16 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название приложения')),
                ('server_name', models.CharField(max_length=50, verbose_name='Имя сервера')),
                ('quota', models.PositiveSmallIntegerField(verbose_name='Количество лицензий')),
            ],
        ),
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('room', models.CharField(max_length=255, verbose_name='Комната')),
                ('quota', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('applications', models.ManyToManyField(related_name='related_room', to='main.Application', verbose_name='Приложения')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staffer', verbose_name='Ответственный сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staffer', verbose_name='Ответственный сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('wait', 'Ожидание'), ('ready', 'Готово'), ('rejection', 'Отказ'), ('completed', 'Окончено')], default='wait', max_length=100, verbose_name='Статус мероприятия')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization', verbose_name='Организация')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staffer', verbose_name='Ответственный сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество участников')),
                ('link_to_event', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время окончания')),
                ('type', models.CharField(choices=[('external', 'Внешний'), ('local', 'Внутренний')], default='local', max_length=100, verbose_name='Тип видеоконференции')),
                ('status', models.CharField(choices=[('wait', 'Ожидание'), ('ready', 'Готово'), ('rejection', 'Отказ'), ('completed', 'Окончено')], default='wait', max_length=100, verbose_name='Статус видеоконференции')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application', verbose_name='Приложение')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event', verbose_name='Мероприятие')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.PositiveSmallIntegerField(verbose_name='Количество участников')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('wait', 'Ожидание'), ('ready', 'Готово'), ('rejection', 'Отказ'), ('completed', 'Окончено')], default='wait', max_length=100, verbose_name='Статус бронирования')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event', verbose_name='Мероприятие')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Место проведения')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staffer', verbose_name='Ответственный сотрудник'),
        ),
    ]
