# Generated by Django 3.1.6 on 2021-02-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.application', verbose_name='Приложение'),
        ),
    ]
