name: CI_CD

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: anra/reg_vcs:latest
      -
        name: Create .env file
        env:
          ENV_FOR_DOCKER_COMPOSE: ${{ secrets.ENV_FOR_DOCKER_COMPOSE }}
        run: echo $ENV_FOR_DOCKER_COMPOSE > .env
      - 
        name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REGVCS_TEST_SERVER_HOST }}
          username: ${{ secrets.REGVCS_TEST_SERVER_USERNAME }}
          port: ${{ secrets.REGVCS_TEST_SERVER_PORT }}
          key: ${{ secrets.REGVCS_TEST_SERVER_KEY }}
          source: "docker-compose.yml, docker/nginx/default.conf, docker/postgres/init.sql, .env"
          target: "/root/app"
